### ISSUE TITLE
Fix box spacing

### ISSUE THREAD

**Issue by stjohnfinn** [braheezy/violet#16] opened 2023-09-22 22:37 UTC
This might be a bubbletea or lipgloss issue?? 

When I run violet I see the standard interface. However, there is one issue:

![image](https://github.com/braheezy/violet/assets/31783902/442901aa-6259-4c7f-be9b-85ce39aab4d5)
Forgive the MS paint recreation.

The right border of the boxes seems to be placed incorrectly. Not sure why this is happening. It does this even with a short 8-character VM name.

**Comment by braheezy** [comment] 2024-02-17 17:51
I'm unable to reproduce this. Can I have more details about the environment used? What OS, terminal emulator, etc.

**Comment by stjohnfinn** [comment] 2024-02-17 18:49
Bruh 😭😭

it was fedora 36 probably using alacritty. Try making the window smaller maybe? Did you update the version of lipgloss/bubble tea you depend on? Maybe it was a bug on their end.

**Comment by braheezy** [comment] 2024-02-17 20:04
yeah dependencies were updated. I ran `violet` in Alacritty and other than having no color(?) the lines are drawn fine. 

Closing for now, feel free to re-open if you see it again.

**Closed by braheezy** 2024-02-17 20:04 UTC
